title: Jouer une seule note
hero_image: images/banner.png
description: Jouer une seule note
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - 
    title: Jouer une seule note
